name: myapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  flutter_local_notifications: ^17.2.4
  intl: ^0.19.0
  timezone: ^0.9.4
  permission_handler: ^11.4.0
  
  # Firebase Dependencies
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  firebase_database: ^11.3.10
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
